import Head from 'next/head';
import NewForm from '@/components/NewForm/NewForm';
import { generateCountryOptions } from '@/server/resources/countries';

interface HomeProps {
  countriesOptions: [];
}

export default function Home({ countriesOptions }: HomeProps) {
  return (
    <>
      <Head>
        <title>Wave Map</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <h1>Home page</h1>
        <NewForm countriesOptions={countriesOptions} />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const countriesOptions = Array(generateCountryOptions());

  return {
    props: {
      countriesOptions: countriesOptions,
    },
  };
}
